# ---------------- APPLICATION ----------------
app.url=https://demowebshop.tricentis.com/
browser=chrome

# ---------------- LOGIN ----------------
login.valid.email=hari01@gmail.com
login.valid.password=HK@0123

login.invalid.email=hari07@gmail.com
login.invalid.password=HK@0577

# ---------------- PRODUCT SEARCH ----------------
product.valid.name=14.1-inch Laptop
product.invalid.name=NonExistingProduct123

# ---------------- CART / CHECKOUT ----------------
product.cart.name=14.1-inch Laptop
product.cart.id=SKU_101

# ---------------- REGISTRATION (VALID) ----------------
reg.valid.gender=male
reg.valid.firstname=Hari
reg.valid.lastname=Krishna
reg.valid.email=hari_new07@gmail.com
reg.valid.password=HK@0123

# ---------------- REGISTRATION (INVALID) ----------------
reg.invalid.gender=female
reg.invalid.firstname=
reg.invalid.lastname=Krishna
reg.invalid.email=NOEMAIL
reg.invalid.password=123
reg.invalid.confirmpassword=456
